from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path


def default_comfy_root() -> Path:
    return (
        Path(os.environ.get("LOCALAPPDATA") or "")
        / "Comfy-Desktop"
        / "ComfyUI-Installs"
        / "ComfyUI"
        / "ComfyUI"
    )


def output_candidates(comfy_root: Path) -> list[Path]:
    local = Path(os.environ.get("LOCALAPPDATA") or "")
    return [
        local / "Comfy-Desktop" / "ComfyUI-Shared" / "output",
        comfy_root / "output",
    ]


def latest_attempt(comfy_root: Path) -> tuple[Path, Path, Path]:
    rows = []
    for output_root in output_candidates(comfy_root):
        attempts = output_root / "conceptghost" / "p10_attempts"
        if not attempts.is_dir():
            continue
        for wan in attempts.rglob("gate5/wan_manifest.json"):
            attempt = wan.parent.parent
            cameras = list((attempt / "gate4").rglob("camera_manifest.json"))
            if not cameras:
                continue
            cameras.sort(key=lambda path: path.stat().st_mtime_ns, reverse=True)
            rows.append((max(wan.stat().st_mtime_ns, cameras[0].stat().st_mtime_ns), attempt, wan, cameras[0]))
    if not rows:
        raise RuntimeError("No reusable P10 attempt with Gate 4 camera manifest + Gate 5 WAN manifest was found")
    rows.sort(key=lambda row: row[0], reverse=True)
    _mtime, attempt, wan, camera = rows[0]
    return attempt, wan, camera


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Resume/rebuild Gate 6 only from the latest existing drone/WAN attempt."
    )
    parser.add_argument("--comfy-root", type=Path, default=default_comfy_root())
    args = parser.parse_args()

    comfy_root = args.comfy_root.resolve()
    custom_nodes = comfy_root / "custom_nodes"
    node_root = custom_nodes / "ConceptGhost_P10_Lab"
    if not (node_root / "__init__.py").is_file():
        raise RuntimeError("ConceptGhost_P10_Lab not found: " + str(node_root))

    attempt, wan_path, camera_path = latest_attempt(comfy_root)
    wan = json.loads(wan_path.read_text(encoding="utf-8"))
    p9_run = Path(str(wan.get("source_p9_run_dir") or "")).expanduser()
    if not p9_run.is_dir():
        control_value = str(wan.get("source_control_manifest") or "").strip()
        if control_value:
            try:
                control = json.loads(Path(control_value).read_text(encoding="utf-8"))
                p9_run = Path(str(control.get("source_p9_run_dir") or "")).expanduser()
            except Exception:
                pass

    sys.path.insert(0, str(comfy_root))
    sys.path.insert(0, str(custom_nodes))
    from ConceptGhost_P10_Lab.reconstruction_runtime import run_reconstruction_pipeline

    print("============================================================")
    print("ConceptGhost R6I - Resume Gate 6 only")
    print("============================================================")
    print("P10 attempt      : " + str(attempt))
    print("WAN manifest     : " + str(wan_path))
    print("Camera manifest  : " + str(camera_path))
    print("P9 run           : " + str(p9_run))
    print("WAN will NOT be regenerated by this helper.")
    print("Existing valid Gate 6 checkpoints will be reused.")
    print("============================================================")

    result = run_reconstruction_pipeline(
        wan_path,
        camera_path,
        attempt / "gate6",
        colmap_executable=None,
        resume=True,
    )
    raw_ply = Path(str(result.get("gate6_raw_p10_geometry_path") or ""))
    raw_obj = Path(str(result.get("gate6_raw_p10_geometry_obj_path") or ""))
    output_manifest = Path(str(result.get("gate6_geometry_output_manifest_path") or ""))

    print(json.dumps({
        "runtime_status": result.get("runtime_status"),
        "geometry_quality_status": result.get("geometry_quality_status"),
        "gate6_geometry_generated": result.get("gate6_geometry_generated"),
        "raw_p10_geometry_ply": str(raw_ply),
        "raw_p10_geometry_obj": str(raw_obj),
        "gate6_geometry_output_manifest": str(output_manifest),
        "p9_run_sidecar_root": result.get("gate6_geometry_output_sidecar_root"),
        "stages": result.get("stages"),
    }, indent=2, default=str))

    if result.get("gate6_geometry_generated") is not True:
        raise RuntimeError("Gate 6 did not publish a geometry_generated=true artifact")
    if not raw_ply.is_file() or not raw_obj.is_file() or not output_manifest.is_file():
        raise RuntimeError("Gate 6 output files are incomplete")

    print("[PASS] Gate 6 published RAW P10 geometry from the existing drone/WAN images.")
    print("[PASS] PLY: " + str(raw_ply))
    print("[PASS] OBJ: " + str(raw_obj))
    if result.get("gate6_geometry_output_sidecar_root"):
        print("[PASS] P9-run sidecar: " + str(result["gate6_geometry_output_sidecar_root"]))
    print("[IMPORTANT] This is BEFORE Gate 7. Inspect this raw mesh to judge whether Gate 6 is actually filling occluded regions.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
