from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path


def default_comfy_root() -> Path:
    return (
        Path(os.environ.get("LOCALAPPDATA") or "")
        / "Comfy-Desktop"
        / "ComfyUI-Installs"
        / "ComfyUI"
        / "ComfyUI"
    )


def default_output_root() -> Path:
    return (
        Path(os.environ.get("LOCALAPPDATA") or "")
        / "Comfy-Desktop"
        / "ComfyUI-Shared"
        / "output"
    )


def latest_failure(output_root: Path) -> Path:
    attempts = output_root / "conceptghost" / "p10_attempts"
    if not attempts.is_dir():
        raise RuntimeError("P10 attempts root not found: " + str(attempts))
    candidates = [
        path
        for path in attempts.rglob("gate7_failure_manifest.json")
        if path.is_file()
    ]
    if not candidates:
        raise RuntimeError("No Gate 7 failure manifest found under: " + str(attempts))
    candidates.sort(key=lambda path: path.stat().st_mtime_ns, reverse=True)
    return candidates[0]


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Resume the latest failed ConceptGhost Gate 7 attempt without rerunning WAN or Gate 6."
    )
    parser.add_argument("--comfy-root", type=Path, default=default_comfy_root())
    parser.add_argument("--output-root", type=Path, default=default_output_root())
    parser.add_argument("--failure-manifest", type=Path)
    args = parser.parse_args()

    comfy_root = args.comfy_root.resolve()
    custom_nodes = comfy_root / "custom_nodes"
    node_root = custom_nodes / "ConceptGhost_P10_Lab"
    if not (node_root / "__init__.py").is_file():
        raise RuntimeError("ConceptGhost_P10_Lab not found: " + str(node_root))

    sys.path.insert(0, str(comfy_root))
    sys.path.insert(0, str(custom_nodes))
    from ConceptGhost_P10_Lab.gate7_runtime import run_gate7_pipeline

    failure_path = (
        args.failure_manifest.resolve()
        if args.failure_manifest
        else latest_failure(args.output_root.resolve())
    )
    failure = json.loads(failure_path.read_text(encoding="utf-8"))
    if failure.get("schema") != "ConceptGhost.P10Gate7Failure.v0.1":
        raise RuntimeError("Not a Gate 7 failure manifest: " + str(failure_path))

    p9_run_dir = Path(str(failure.get("p9_run_dir") or "")).resolve()
    gate6_manifest = Path(str(failure.get("gate6_runtime_manifest_path") or "")).resolve()
    attempt_root = Path(str(failure.get("p10_attempt_root") or "")).resolve()

    if not p9_run_dir.is_dir():
        raise RuntimeError("P9 run directory missing: " + str(p9_run_dir))
    if not gate6_manifest.is_file():
        raise RuntimeError("Gate 6 runtime manifest missing: " + str(gate6_manifest))
    if not attempt_root.is_dir():
        raise RuntimeError("P10 attempt root missing: " + str(attempt_root))

    print("============================================================")
    print("ConceptGhost R6F15 - Resume Gate 7 only")
    print("============================================================")
    print("Failure manifest : " + str(failure_path))
    print("Failed stage     : " + str(failure.get("failed_stage")))
    print("P9 run           : " + str(p9_run_dir))
    print("P10 attempt      : " + str(attempt_root))
    print("Gate 6 manifest  : " + str(gate6_manifest))
    print("WAN and Gate 6 will NOT be regenerated by this helper.")
    print("============================================================")

    result = run_gate7_pipeline(
        p9_run_dir,
        gate6_manifest,
        output_root=attempt_root / "gate7",
        resume_existing=True,
        run_delaunay=True,
        colmap_executable="",
    )
    print(
        json.dumps(
            {
                "status": result.get("status"),
                "manifest_path": result.get("manifest_path"),
                "artifacts": result.get("artifacts"),
                "auto_audit": result.get("auto_audit"),
            },
            indent=2,
            default=str,
        )
    )
    if result.get("status") != "PASS":
        raise RuntimeError("Gate 7 resume did not return PASS")

    print("[PASS] Gate 7 completed from the existing attempt.")
    print("[PASS] Existing WAN/Gate 6 artifacts were reused; no new Production attempt was created.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
